[build]
  functions = "netlify/functions"
  publish = "site"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
  from = "/nawaf-ZsN8pU0E"
  to = "/nawaf-ZsN8pU0E.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions."academy-sync-cron"]
  schedule = "*/5 * * * *"

[functions."tweet-cron"]
  schedule = "@hourly"
